CREATE TABLE Volunteers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    firstName VARCHAR(50),
    lastName VARCHAR(50),
    email VARCHAR(100),
    phone VARCHAR(15),
    whyHelp VARCHAR(300)
);

CREATE TABLE WebsiteInfo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    headerMessage VARCHAR(500),
    numMeals VARCHAR(6)
);
